/**
 * ----------------------------------------------------------------------------
 * File: index.js
 * Authors:
 *      Amey Thakur
 *      GitHub: https://github.com/ameythakur
 *
 *      Mega Satish
 *      GitHub: https://github.com/msatmod
 *
 * Repository: https://github.com/Amey-Thakur/REACT-TODO-APP
 * License: MIT License
 * Release Date: June 25, 2022
 * ----------------------------------------------------------------------------
 *
 * File Overview:
 * This file is the specific entry point for the React application. It handles:
 * 1. Mounting the React component tree into the DOM.
 * 2. Enabling Strict Mode for highlighting potential problems.
 * 3. Registering the Service Worker for PWA capabilities (offline support).
 * 4. Initializing performance monitoring via Web Vitals.
 *
 */

import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import TodoApp from './TodoApp';
import reportWebVitals from './reportWebVitals';
import * as serviceWorkerRegistration from './serviceWorkerRegistration';

// Initialize the root React root based on the DOM element with ID 'root'
const root = ReactDOM.createRoot(document.getElementById('root'));

// Render the application tree
root.render(
  <React.StrictMode>
    <TodoApp />
  </React.StrictMode>
);

// PWA: Allow offline functionality and standalone installation
// This registers the service worker generated by the build process.
serviceWorkerRegistration.register();

// Performance Monitoring
// Pass a function to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
